# Script (and install-tomcat.sh) built on concepts from https://www.ubuntumint.com/install-apache-tomcat-rhel-9/

- name: Pre-requisites
  hosts: alfresco
  tasks:
    - name: "Install dependencies"
      become: true
      ansible.builtin.dnf:
        name:
          - java-17-openjdk
          - tar

    - name: "SELinux settings"
      become: true
      ansible.builtin.shell: |
        if [[ "$(grep -Eo '^SELINUX=disabled$' /etc/selinux/config | wc -l)" == "0" ]]; then
          setenforce 0;
          sed -i 's/SELINUX=.*$/SELINUX=disabled/g' /etc/selinux/config;
        fi

- name: Install Tomcat
  # based on https://www.ubuntumint.com/install-apache-tomcat-rhel-9/
  hosts: alfresco
  tasks:
    - name: Create user
      become: true
      ansible.builtin.user:
        name: tomcat

    - name: Copy systemctl service
      become: true
      ansible.builtin.copy:
        src: ${ansible_work_dir}/alfresco/tomcat.service
        dest: /etc/systemd/system/tomcat.service
        mode: '0644'

    - name: Create installs directory
      become: true
      become_user: tomcat
      ansible.builtin.file:
        state: directory
        path: /home/tomcat/installs
        mode: '0755'

    - name: Download and extract
      become: true
      become_user: tomcat
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v${tomcat_version}/bin/apache-tomcat-${tomcat_version}.tar.gz
        remote_src: yes
        dest: /home/tomcat/installs
        creates: /home/tomcat/installs/apache-tomcat-${tomcat_version}

    - name: Send config files
      become: true
      ansible.builtin.copy: "{{item}}"
      loop:
        - src: ${ansible_work_dir}/alfresco/tomcat-users.xml
          dest: /home/tomcat/installs/apache-tomcat-${tomcat_version}/conf/tomcat-users.xml
          owner: tomcat
          group: tomcat
          mode: '0600'
        - src: ${ansible_work_dir}/alfresco/tomcat-context.xml
          dest: /home/tomcat/installs/apache-tomcat-${tomcat_version}/webapps/manager/META-INF/context.xml
          owner: tomcat
          group: tomcat
          mode: '0640'

    - name: Create symlink
      become: true
      ansible.builtin.file:
        state: link
        src: /home/tomcat/installs/apache-tomcat-${tomcat_version}
        dest: /usr/local/tomcat10
        owner: tomcat
        group: tomcat

    - name: "Start Tomcat"
      become: true
      ansible.builtin.shell: "{{item}}"
      loop:
        - systemctl daemon-reload
        - systemctl enable tomcat
        - systemctl start tomcat
      register: start_result
