CREATE TABLE Employees
(
    EmployeeID NUMBER PRIMARY KEY,
    EmployeeName VARCHAR(50) ,
    EmployeeAddress VARCHAR(50) ,
    MonthSalary NUMERIC(10, 2)
);
INSERT INTO EMPLOYEES (EMPLOYEEID, EMPLOYEENAME, EMPLOYEEADDRESS, MONTHSALARY) VALUES(1, 'Marge Simpson', '37 Evergreen Tce', 500);
INSERT INTO EMPLOYEES (EMPLOYEEID, EMPLOYEENAME, EMPLOYEEADDRESS, MONTHSALARY) VALUES(2, 'Homer Simpson', '37 Evergreen Tce', 550);
INSERT INTO EMPLOYEES (EMPLOYEEID, EMPLOYEENAME, EMPLOYEEADDRESS, MONTHSALARY) VALUES(3, 'Bart Simpson', '37 Evergreen Tce', 550);
INSERT INTO EMPLOYEES (EMPLOYEEID, EMPLOYEENAME, EMPLOYEEADDRESS, MONTHSALARY) VALUES(4, 'Lisa Simpson', '37 Evergreen Tce', 550);
INSERT INTO EMPLOYEES (EMPLOYEEID, EMPLOYEENAME, EMPLOYEEADDRESS, MONTHSALARY) VALUES(5, 'Maggie Simpson', '37 Evergreen Tce', 550);


SELECT * FROM EMPLOYEES e ;
